import { createClient } from "@supabase/supabase-js";
import { executeSkill } from "@/lib/nour-run.server";
const c = createClient(process.env["SUPABASE_URL"]!, process.env["SUPABASE_SERVICE_ROLE_KEY"]!, { auth: { persistSession: false } });
const { data: ws } = await c.from("workspaces").select("id").limit(1).single();
const r = await executeSkill(c as any, { workspaceId: (ws as any).id, employeeId: "nour", skillId: "seo-article", values: { topic: "طريقة تحضير قهوة V60", keyword: "قهوة v60" }, origin: "اختبار صور" });
const m = r.output.match(/!\[[^\]]*\]\(([^)]+)\)/);
console.log("hero:", m?.[1]?.slice(0,120));
console.log(r.output.slice(0, 300));
const r2 = await executeSkill(c as any, { workspaceId: (ws as any).id, employeeId: "nour", skillId: "daily-ideas", values: { topic: "قهوة مختصة" }, origin: "اختبار" });
console.log("ideas chars:", r2.output.length, r2.output.slice(0,200));
process.exit(0);
